# Generated by Django 3.2.15 on 2022-09-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('start_network', models.CharField(max_length=15)),
                ('start_ticker', models.CharField(max_length=10)),
                ('start_amount', models.IntegerField()),
                ('start_usd_amt', models.IntegerField()),
                ('post_platform', models.CharField(max_length=30)),
                ('post_amount', models.CharField(max_length=10)),
                ('post_tickers', models.CharField(max_length=30)),
                ('post_usd_amt', models.IntegerField()),
                ('end_usd_amt', models.IntegerField()),
                ('end_date', models.DateField()),
                ('profit_loss_percent', models.IntegerField()),
                ('profit_loss_usd_amt', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('deadline', models.DateField()),
            ],
        ),
    ]
