# Generated by Django 3.2.15 on 2022-09-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
