# Generated by Django 3.2.15 on 2022-09-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_alter_trade_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='trade',
            name='end_usd_amt',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trade',
            name='post_usd_amt',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trade',
            name='profit_loss_percent',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trade',
            name='profit_loss_usd_amt',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trade',
            name='start_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trade',
            name='start_usd_amt',
            field=models.FloatField(),
        ),
    ]
